apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-hello-1
spec:
  selector:
    matchLabels:
      app: laravel-hello-1
  replicas: 1
  template:
    metadata:
      labels:
        app: laravel-hello-1
    spec:
      nodeName: worker-node1
      containers:
        - name: laravel-hello-1
          image: asrafhasib/laravel-hello-1:${BUILD_NUMBER}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
----------
apiVersion: v1
kind: Service
metadata:
  name: laravel-hello-1-service
spec:
  selector:
    app: laravel-hello-1
  ports:
    - protocol: "TCP"
      port: 80
  type: NodePort
